<?php

namespace Database\Seeders;

use App\Models\BannerPlacementDefinition;
use Illuminate\Database\Seeder;

class BannerPlacementDefinitionsSeeder extends Seeder
{
    public function run(): void
    {
        $placements = [
            [
                'code'                   => 'homepage_hero',
                'name'                   => 'Homepage Hero',
                'description'            => 'Large hero banner at the top of the homepage.',
                'width_px'               => 1440,
                'height_px'              => 480,
                'max_file_size_kb'       => 512,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'desktop',
                'max_simultaneous'       => 1,
                'supports_vendor_ads'    => false,
                'base_rate_weekly' => 50000,
                'is_active'              => true,
                'sort_order'             => 10,
            ],
            [
                'code'                   => 'homepage_secondary_left',
                'name'                   => 'Homepage Secondary – Left',
                'description'            => 'Secondary banner slot on the left side of the homepage.',
                'width_px'               => 600,
                'height_px'              => 300,
                'max_file_size_kb'       => 256,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'all',
                'max_simultaneous'       => 1,
                'supports_vendor_ads'    => true,
                'base_rate_weekly' => 25000,
                'is_active'              => true,
                'sort_order'             => 20,
            ],
            [
                'code'                   => 'homepage_secondary_right',
                'name'                   => 'Homepage Secondary – Right',
                'description'            => 'Secondary banner slot on the right side of the homepage.',
                'width_px'               => 600,
                'height_px'              => 300,
                'max_file_size_kb'       => 256,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'all',
                'max_simultaneous'       => 1,
                'supports_vendor_ads'    => true,
                'base_rate_weekly' => 25000,
                'is_active'              => true,
                'sort_order'             => 30,
            ],
            [
                'code'                   => 'homepage_midpage',
                'name'                   => 'Homepage Mid-page',
                'description'            => 'Wide mid-page banner on the homepage.',
                'width_px'               => 1440,
                'height_px'              => 300,
                'max_file_size_kb'       => 400,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'all',
                'max_simultaneous'       => 2,
                'supports_vendor_ads'    => true,
                'base_rate_weekly' => 30000,
                'is_active'              => true,
                'sort_order'             => 40,
            ],
            [
                'code'                   => 'category_top',
                'name'                   => 'Category – Top Banner',
                'description'            => 'Banner at the top of category listing pages.',
                'width_px'               => 1200,
                'height_px'              => 150,
                'max_file_size_kb'       => 256,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'all',
                'max_simultaneous'       => 1,
                'supports_vendor_ads'    => true,
                'base_rate_weekly' => 20000,
                'is_active'              => true,
                'sort_order'             => 50,
            ],
            [
                'code'                   => 'category_sidebar',
                'name'                   => 'Category – Sidebar',
                'description'            => 'Sidebar banner on category pages (desktop only).',
                'width_px'               => 300,
                'height_px'              => 600,
                'max_file_size_kb'       => 256,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'desktop',
                'max_simultaneous'       => 2,
                'supports_vendor_ads'    => true,
                'base_rate_weekly' => 15000,
                'is_active'              => true,
                'sort_order'             => 60,
            ],
            [
                'code'                   => 'search_top',
                'name'                   => 'Search Results – Top',
                'description'            => 'Banner above search results.',
                'width_px'               => 1200,
                'height_px'              => 150,
                'max_file_size_kb'       => 256,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'all',
                'max_simultaneous'       => 1,
                'supports_vendor_ads'    => false,
                'base_rate_weekly' => 20000,
                'is_active'              => true,
                'sort_order'             => 70,
            ],
            [
                'code'                   => 'cart_banner',
                'name'                   => 'Cart Page Banner',
                'description'            => 'Promotional banner on the shopping cart page.',
                'width_px'               => 900,
                'height_px'              => 200,
                'max_file_size_kb'       => 200,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'all',
                'max_simultaneous'       => 1,
                'supports_vendor_ads'    => false,
                'base_rate_weekly' => 18000,
                'is_active'              => true,
                'sort_order'             => 80,
            ],
            [
                'code'                   => 'checkout_banner',
                'name'                   => 'Checkout Page Banner',
                'description'            => 'Promotional banner on the checkout page.',
                'width_px'               => 900,
                'height_px'              => 200,
                'max_file_size_kb'       => 200,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'all',
                'max_simultaneous'       => 1,
                'supports_vendor_ads'    => false,
                'base_rate_weekly' => 18000,
                'is_active'              => true,
                'sort_order'             => 90,
            ],
            [
                'code'                   => 'product_page_bottom',
                'name'                   => 'Product Page – Bottom',
                'description'            => 'Banner at the bottom of product detail pages.',
                'width_px'               => 1200,
                'height_px'              => 200,
                'max_file_size_kb'       => 256,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'all',
                'max_simultaneous'       => 1,
                'supports_vendor_ads'    => true,
                'base_rate_weekly' => 15000,
                'is_active'              => true,
                'sort_order'             => 100,
            ],
            [
                'code'                   => 'app_splash',
                'name'                   => 'App Splash Screen',
                'description'            => 'Full-screen splash banner in the mobile app.',
                'width_px'               => 375,
                'height_px'              => 667,
                'max_file_size_kb'       => 300,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'app',
                'max_simultaneous'       => 1,
                'supports_vendor_ads'    => false,
                'base_rate_weekly' => 35000,
                'is_active'              => true,
                'sort_order'             => 110,
            ],
            [
                'code'                   => 'app_home_top',
                'name'                   => 'App Home – Top Banner',
                'description'            => 'Top banner on the mobile app home screen.',
                'width_px'               => 375,
                'height_px'              => 200,
                'max_file_size_kb'       => 200,
                'allowed_formats'        => ['jpg', 'jpeg', 'png', 'webp'],
                'device_restriction'     => 'app',
                'max_simultaneous'       => 3,
                'supports_vendor_ads'    => true,
                'base_rate_weekly' => 28000,
                'is_active'              => true,
                'sort_order'             => 120,
            ],
            [
                'code'                   => 'email_header',
                'name'                   => 'Email Header Banner',
                'description'            => 'Banner used in email campaign headers.',
                'width_px'               => 600,
                'height_px'              => 200,
                'max_file_size_kb'       => 150,
                'allowed_formats'        => ['jpg', 'jpeg', 'png'],
                'device_restriction'     => 'all',
                'max_simultaneous'       => 1,
                'supports_vendor_ads'    => false,
                'base_rate_weekly' => 12000,
                'is_active'              => true,
                'sort_order'             => 130,
            ],
        ];

        foreach ($placements as $placement) {
            $code = $placement['code'];
            $attributes = array_diff_key($placement, ['code' => null]);

            BannerPlacementDefinition::firstOrCreate(
                ['code' => $code],
                $attributes
            );
        }
    }
}
