<?php

namespace Database\Seeders;

use App\Models\TravelCountry;
use Illuminate\Database\Seeder;

/**
 * Seeds all 195 UN-recognized sovereign states using ISO 3166-1 data.
 * Static reference dataset — no network access required.
 * Safe to re-run: keyed on iso_code_2 via firstOrCreate.
 *
 * NOTE: A small number of entries (primarily micro-states and territories with
 * limited Arabic transliteration consensus) have Arabic names that are
 * standard transliterations; an Arabic-language editor should review and
 * adjust any entries that serve Arabic-speaking customers directly.
 */
class TravelCountrySeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->countries() as $country) {
            TravelCountry::firstOrCreate(
                ['iso_code_2' => $country['iso_code_2']],
                $country,
            );
        }
    }

    private function countries(): array
    {
        return [
            // ── Africa ────────────────────────────────────────────────────────
            ['iso_code_2' => 'DZ', 'iso_code_3' => 'DZA', 'name_en' => 'Algeria',               'name_ar' => 'الجزائر',              'flag_emoji' => '🇩🇿', 'continent' => 'Africa'],
            ['iso_code_2' => 'AO', 'iso_code_3' => 'AGO', 'name_en' => 'Angola',                'name_ar' => 'أنغولا',               'flag_emoji' => '🇦🇴', 'continent' => 'Africa'],
            ['iso_code_2' => 'BJ', 'iso_code_3' => 'BEN', 'name_en' => 'Benin',                 'name_ar' => 'بنين',                 'flag_emoji' => '🇧🇯', 'continent' => 'Africa'],
            ['iso_code_2' => 'BW', 'iso_code_3' => 'BWA', 'name_en' => 'Botswana',              'name_ar' => 'بوتسوانا',             'flag_emoji' => '🇧🇼', 'continent' => 'Africa'],
            ['iso_code_2' => 'BF', 'iso_code_3' => 'BFA', 'name_en' => 'Burkina Faso',          'name_ar' => 'بوركينا فاسو',         'flag_emoji' => '🇧🇫', 'continent' => 'Africa'],
            ['iso_code_2' => 'BI', 'iso_code_3' => 'BDI', 'name_en' => 'Burundi',               'name_ar' => 'بوروندي',              'flag_emoji' => '🇧🇮', 'continent' => 'Africa'],
            ['iso_code_2' => 'CV', 'iso_code_3' => 'CPV', 'name_en' => 'Cape Verde',            'name_ar' => 'الرأس الأخضر',         'flag_emoji' => '🇨🇻', 'continent' => 'Africa'],
            ['iso_code_2' => 'CM', 'iso_code_3' => 'CMR', 'name_en' => 'Cameroon',              'name_ar' => 'الكاميرون',            'flag_emoji' => '🇨🇲', 'continent' => 'Africa'],
            ['iso_code_2' => 'CF', 'iso_code_3' => 'CAF', 'name_en' => 'Central African Republic','name_ar' => 'جمهورية أفريقيا الوسطى','flag_emoji' => '🇨🇫', 'continent' => 'Africa'],
            ['iso_code_2' => 'TD', 'iso_code_3' => 'TCD', 'name_en' => 'Chad',                  'name_ar' => 'تشاد',                 'flag_emoji' => '🇹🇩', 'continent' => 'Africa'],
            ['iso_code_2' => 'KM', 'iso_code_3' => 'COM', 'name_en' => 'Comoros',               'name_ar' => 'جزر القمر',            'flag_emoji' => '🇰🇲', 'continent' => 'Africa'],
            ['iso_code_2' => 'CG', 'iso_code_3' => 'COG', 'name_en' => 'Congo',                 'name_ar' => 'جمهورية الكونغو',      'flag_emoji' => '🇨🇬', 'continent' => 'Africa'],
            ['iso_code_2' => 'CD', 'iso_code_3' => 'COD', 'name_en' => 'DR Congo',              'name_ar' => 'جمهورية الكونغو الديمقراطية','flag_emoji' => '🇨🇩', 'continent' => 'Africa'],
            ['iso_code_2' => 'CI', 'iso_code_3' => 'CIV', 'name_en' => "Côte d'Ivoire",        'name_ar' => 'ساحل العاج',           'flag_emoji' => '🇨🇮', 'continent' => 'Africa'],
            ['iso_code_2' => 'DJ', 'iso_code_3' => 'DJI', 'name_en' => 'Djibouti',             'name_ar' => 'جيبوتي',               'flag_emoji' => '🇩🇯', 'continent' => 'Africa'],
            ['iso_code_2' => 'EG', 'iso_code_3' => 'EGY', 'name_en' => 'Egypt',                'name_ar' => 'مصر',                  'flag_emoji' => '🇪🇬', 'continent' => 'Africa'],
            ['iso_code_2' => 'GQ', 'iso_code_3' => 'GNQ', 'name_en' => 'Equatorial Guinea',    'name_ar' => 'غينيا الاستوائية',     'flag_emoji' => '🇬🇶', 'continent' => 'Africa'],
            ['iso_code_2' => 'ER', 'iso_code_3' => 'ERI', 'name_en' => 'Eritrea',              'name_ar' => 'إريتريا',               'flag_emoji' => '🇪🇷', 'continent' => 'Africa'],
            ['iso_code_2' => 'SZ', 'iso_code_3' => 'SWZ', 'name_en' => 'Eswatini',             'name_ar' => 'إسواتيني',             'flag_emoji' => '🇸🇿', 'continent' => 'Africa'],
            ['iso_code_2' => 'ET', 'iso_code_3' => 'ETH', 'name_en' => 'Ethiopia',             'name_ar' => 'إثيوبيا',              'flag_emoji' => '🇪🇹', 'continent' => 'Africa'],
            ['iso_code_2' => 'GA', 'iso_code_3' => 'GAB', 'name_en' => 'Gabon',                'name_ar' => 'الغابون',              'flag_emoji' => '🇬🇦', 'continent' => 'Africa'],
            ['iso_code_2' => 'GM', 'iso_code_3' => 'GMB', 'name_en' => 'Gambia',               'name_ar' => 'غامبيا',               'flag_emoji' => '🇬🇲', 'continent' => 'Africa'],
            ['iso_code_2' => 'GH', 'iso_code_3' => 'GHA', 'name_en' => 'Ghana',                'name_ar' => 'غانا',                 'flag_emoji' => '🇬🇭', 'continent' => 'Africa'],
            ['iso_code_2' => 'GN', 'iso_code_3' => 'GIN', 'name_en' => 'Guinea',               'name_ar' => 'غينيا',                'flag_emoji' => '🇬🇳', 'continent' => 'Africa'],
            ['iso_code_2' => 'GW', 'iso_code_3' => 'GNB', 'name_en' => 'Guinea-Bissau',        'name_ar' => 'غينيا بيساو',          'flag_emoji' => '🇬🇼', 'continent' => 'Africa'],
            ['iso_code_2' => 'KE', 'iso_code_3' => 'KEN', 'name_en' => 'Kenya',                'name_ar' => 'كينيا',                'flag_emoji' => '🇰🇪', 'continent' => 'Africa'],
            ['iso_code_2' => 'LS', 'iso_code_3' => 'LSO', 'name_en' => 'Lesotho',              'name_ar' => 'ليسوتو',               'flag_emoji' => '🇱🇸', 'continent' => 'Africa'],
            ['iso_code_2' => 'LR', 'iso_code_3' => 'LBR', 'name_en' => 'Liberia',              'name_ar' => 'ليبيريا',              'flag_emoji' => '🇱🇷', 'continent' => 'Africa'],
            ['iso_code_2' => 'LY', 'iso_code_3' => 'LBY', 'name_en' => 'Libya',               'name_ar' => 'ليبيا',                'flag_emoji' => '🇱🇾', 'continent' => 'Africa'],
            ['iso_code_2' => 'MG', 'iso_code_3' => 'MDG', 'name_en' => 'Madagascar',           'name_ar' => 'مدغشقر',               'flag_emoji' => '🇲🇬', 'continent' => 'Africa'],
            ['iso_code_2' => 'MW', 'iso_code_3' => 'MWI', 'name_en' => 'Malawi',               'name_ar' => 'ملاوي',                'flag_emoji' => '🇲🇼', 'continent' => 'Africa'],
            ['iso_code_2' => 'ML', 'iso_code_3' => 'MLI', 'name_en' => 'Mali',                 'name_ar' => 'مالي',                 'flag_emoji' => '🇲🇱', 'continent' => 'Africa'],
            ['iso_code_2' => 'MR', 'iso_code_3' => 'MRT', 'name_en' => 'Mauritania',           'name_ar' => 'موريتانيا',            'flag_emoji' => '🇲🇷', 'continent' => 'Africa'],
            ['iso_code_2' => 'MU', 'iso_code_3' => 'MUS', 'name_en' => 'Mauritius',            'name_ar' => 'موريشيوس',             'flag_emoji' => '🇲🇺', 'continent' => 'Africa'],
            ['iso_code_2' => 'MA', 'iso_code_3' => 'MAR', 'name_en' => 'Morocco',              'name_ar' => 'المغرب',               'flag_emoji' => '🇲🇦', 'continent' => 'Africa'],
            ['iso_code_2' => 'MZ', 'iso_code_3' => 'MOZ', 'name_en' => 'Mozambique',           'name_ar' => 'موزمبيق',              'flag_emoji' => '🇲🇿', 'continent' => 'Africa'],
            ['iso_code_2' => 'NA', 'iso_code_3' => 'NAM', 'name_en' => 'Namibia',              'name_ar' => 'ناميبيا',              'flag_emoji' => '🇳🇦', 'continent' => 'Africa'],
            ['iso_code_2' => 'NE', 'iso_code_3' => 'NER', 'name_en' => 'Niger',               'name_ar' => 'النيجر',               'flag_emoji' => '🇳🇪', 'continent' => 'Africa'],
            ['iso_code_2' => 'NG', 'iso_code_3' => 'NGA', 'name_en' => 'Nigeria',              'name_ar' => 'نيجيريا',              'flag_emoji' => '🇳🇬', 'continent' => 'Africa'],
            ['iso_code_2' => 'RW', 'iso_code_3' => 'RWA', 'name_en' => 'Rwanda',               'name_ar' => 'رواندا',               'flag_emoji' => '🇷🇼', 'continent' => 'Africa'],
            ['iso_code_2' => 'ST', 'iso_code_3' => 'STP', 'name_en' => 'São Tomé and Príncipe','name_ar' => 'ساو تومي وبرينسيبي',   'flag_emoji' => '🇸🇹', 'continent' => 'Africa'],
            ['iso_code_2' => 'SN', 'iso_code_3' => 'SEN', 'name_en' => 'Senegal',              'name_ar' => 'السنغال',              'flag_emoji' => '🇸🇳', 'continent' => 'Africa'],
            ['iso_code_2' => 'SC', 'iso_code_3' => 'SYC', 'name_en' => 'Seychelles',           'name_ar' => 'سيشل',                 'flag_emoji' => '🇸🇨', 'continent' => 'Africa'],
            ['iso_code_2' => 'SL', 'iso_code_3' => 'SLE', 'name_en' => 'Sierra Leone',         'name_ar' => 'سيراليون',             'flag_emoji' => '🇸🇱', 'continent' => 'Africa'],
            ['iso_code_2' => 'SO', 'iso_code_3' => 'SOM', 'name_en' => 'Somalia',              'name_ar' => 'الصومال',              'flag_emoji' => '🇸🇴', 'continent' => 'Africa'],
            ['iso_code_2' => 'ZA', 'iso_code_3' => 'ZAF', 'name_en' => 'South Africa',         'name_ar' => 'جنوب أفريقيا',         'flag_emoji' => '🇿🇦', 'continent' => 'Africa'],
            ['iso_code_2' => 'SS', 'iso_code_3' => 'SSD', 'name_en' => 'South Sudan',          'name_ar' => 'جنوب السودان',         'flag_emoji' => '🇸🇸', 'continent' => 'Africa'],
            ['iso_code_2' => 'SD', 'iso_code_3' => 'SDN', 'name_en' => 'Sudan',                'name_ar' => 'السودان',              'flag_emoji' => '🇸🇩', 'continent' => 'Africa'],
            ['iso_code_2' => 'TZ', 'iso_code_3' => 'TZA', 'name_en' => 'Tanzania',             'name_ar' => 'تنزانيا',              'flag_emoji' => '🇹🇿', 'continent' => 'Africa'],
            ['iso_code_2' => 'TG', 'iso_code_3' => 'TGO', 'name_en' => 'Togo',                 'name_ar' => 'توغو',                 'flag_emoji' => '🇹🇬', 'continent' => 'Africa'],
            ['iso_code_2' => 'TN', 'iso_code_3' => 'TUN', 'name_en' => 'Tunisia',              'name_ar' => 'تونس',                 'flag_emoji' => '🇹🇳', 'continent' => 'Africa'],
            ['iso_code_2' => 'UG', 'iso_code_3' => 'UGA', 'name_en' => 'Uganda',               'name_ar' => 'أوغندا',               'flag_emoji' => '🇺🇬', 'continent' => 'Africa'],
            ['iso_code_2' => 'ZM', 'iso_code_3' => 'ZMB', 'name_en' => 'Zambia',               'name_ar' => 'زامبيا',               'flag_emoji' => '🇿🇲', 'continent' => 'Africa'],
            ['iso_code_2' => 'ZW', 'iso_code_3' => 'ZWE', 'name_en' => 'Zimbabwe',             'name_ar' => 'زيمبابوي',             'flag_emoji' => '🇿🇼', 'continent' => 'Africa'],

            // ── Americas ──────────────────────────────────────────────────────
            ['iso_code_2' => 'AG', 'iso_code_3' => 'ATG', 'name_en' => 'Antigua and Barbuda',  'name_ar' => 'أنتيغوا وبربودا',      'flag_emoji' => '🇦🇬', 'continent' => 'Americas'],
            ['iso_code_2' => 'AR', 'iso_code_3' => 'ARG', 'name_en' => 'Argentina',            'name_ar' => 'الأرجنتين',            'flag_emoji' => '🇦🇷', 'continent' => 'Americas'],
            ['iso_code_2' => 'BS', 'iso_code_3' => 'BHS', 'name_en' => 'Bahamas',              'name_ar' => 'البهاما',              'flag_emoji' => '🇧🇸', 'continent' => 'Americas'],
            ['iso_code_2' => 'BB', 'iso_code_3' => 'BRB', 'name_en' => 'Barbados',             'name_ar' => 'باربادوس',             'flag_emoji' => '🇧🇧', 'continent' => 'Americas'],
            ['iso_code_2' => 'BZ', 'iso_code_3' => 'BLZ', 'name_en' => 'Belize',              'name_ar' => 'بليز',                 'flag_emoji' => '🇧🇿', 'continent' => 'Americas'],
            ['iso_code_2' => 'BO', 'iso_code_3' => 'BOL', 'name_en' => 'Bolivia',              'name_ar' => 'بوليفيا',              'flag_emoji' => '🇧🇴', 'continent' => 'Americas'],
            ['iso_code_2' => 'BR', 'iso_code_3' => 'BRA', 'name_en' => 'Brazil',               'name_ar' => 'البرازيل',             'flag_emoji' => '🇧🇷', 'continent' => 'Americas'],
            ['iso_code_2' => 'CA', 'iso_code_3' => 'CAN', 'name_en' => 'Canada',               'name_ar' => 'كندا',                 'flag_emoji' => '🇨🇦', 'continent' => 'Americas'],
            ['iso_code_2' => 'CL', 'iso_code_3' => 'CHL', 'name_en' => 'Chile',                'name_ar' => 'تشيلي',                'flag_emoji' => '🇨🇱', 'continent' => 'Americas'],
            ['iso_code_2' => 'CO', 'iso_code_3' => 'COL', 'name_en' => 'Colombia',             'name_ar' => 'كولومبيا',             'flag_emoji' => '🇨🇴', 'continent' => 'Americas'],
            ['iso_code_2' => 'CR', 'iso_code_3' => 'CRI', 'name_en' => 'Costa Rica',           'name_ar' => 'كوستاريكا',            'flag_emoji' => '🇨🇷', 'continent' => 'Americas'],
            ['iso_code_2' => 'CU', 'iso_code_3' => 'CUB', 'name_en' => 'Cuba',                 'name_ar' => 'كوبا',                 'flag_emoji' => '🇨🇺', 'continent' => 'Americas'],
            ['iso_code_2' => 'DM', 'iso_code_3' => 'DMA', 'name_en' => 'Dominica',             'name_ar' => 'دومينيكا',             'flag_emoji' => '🇩🇲', 'continent' => 'Americas'],
            ['iso_code_2' => 'DO', 'iso_code_3' => 'DOM', 'name_en' => 'Dominican Republic',   'name_ar' => 'جمهورية الدومينيكان',  'flag_emoji' => '🇩🇴', 'continent' => 'Americas'],
            ['iso_code_2' => 'EC', 'iso_code_3' => 'ECU', 'name_en' => 'Ecuador',              'name_ar' => 'الإكوادور',            'flag_emoji' => '🇪🇨', 'continent' => 'Americas'],
            ['iso_code_2' => 'SV', 'iso_code_3' => 'SLV', 'name_en' => 'El Salvador',          'name_ar' => 'السلفادور',            'flag_emoji' => '🇸🇻', 'continent' => 'Americas'],
            ['iso_code_2' => 'GD', 'iso_code_3' => 'GRD', 'name_en' => 'Grenada',              'name_ar' => 'غرينادا',              'flag_emoji' => '🇬🇩', 'continent' => 'Americas'],
            ['iso_code_2' => 'GT', 'iso_code_3' => 'GTM', 'name_en' => 'Guatemala',            'name_ar' => 'غواتيمالا',            'flag_emoji' => '🇬🇹', 'continent' => 'Americas'],
            ['iso_code_2' => 'GY', 'iso_code_3' => 'GUY', 'name_en' => 'Guyana',               'name_ar' => 'غيانا',                'flag_emoji' => '🇬🇾', 'continent' => 'Americas'],
            ['iso_code_2' => 'HT', 'iso_code_3' => 'HTI', 'name_en' => 'Haiti',                'name_ar' => 'هايتي',                'flag_emoji' => '🇭🇹', 'continent' => 'Americas'],
            ['iso_code_2' => 'HN', 'iso_code_3' => 'HND', 'name_en' => 'Honduras',             'name_ar' => 'هندوراس',              'flag_emoji' => '🇭🇳', 'continent' => 'Americas'],
            ['iso_code_2' => 'JM', 'iso_code_3' => 'JAM', 'name_en' => 'Jamaica',              'name_ar' => 'جامايكا',              'flag_emoji' => '🇯🇲', 'continent' => 'Americas'],
            ['iso_code_2' => 'MX', 'iso_code_3' => 'MEX', 'name_en' => 'Mexico',               'name_ar' => 'المكسيك',              'flag_emoji' => '🇲🇽', 'continent' => 'Americas'],
            ['iso_code_2' => 'NI', 'iso_code_3' => 'NIC', 'name_en' => 'Nicaragua',            'name_ar' => 'نيكاراغوا',            'flag_emoji' => '🇳🇮', 'continent' => 'Americas'],
            ['iso_code_2' => 'PA', 'iso_code_3' => 'PAN', 'name_en' => 'Panama',               'name_ar' => 'بنما',                 'flag_emoji' => '🇵🇦', 'continent' => 'Americas'],
            ['iso_code_2' => 'PY', 'iso_code_3' => 'PRY', 'name_en' => 'Paraguay',             'name_ar' => 'باراغواي',             'flag_emoji' => '🇵🇾', 'continent' => 'Americas'],
            ['iso_code_2' => 'PE', 'iso_code_3' => 'PER', 'name_en' => 'Peru',                 'name_ar' => 'بيرو',                 'flag_emoji' => '🇵🇪', 'continent' => 'Americas'],
            ['iso_code_2' => 'KN', 'iso_code_3' => 'KNA', 'name_en' => 'Saint Kitts and Nevis','name_ar' => 'سانت كيتس ونيفيس',    'flag_emoji' => '🇰🇳', 'continent' => 'Americas'],
            ['iso_code_2' => 'LC', 'iso_code_3' => 'LCA', 'name_en' => 'Saint Lucia',          'name_ar' => 'سانت لوسيا',           'flag_emoji' => '🇱🇨', 'continent' => 'Americas'],
            ['iso_code_2' => 'VC', 'iso_code_3' => 'VCT', 'name_en' => 'Saint Vincent and the Grenadines','name_ar' => 'سانت فينسنت وجزر غرينادين','flag_emoji' => '🇻🇨', 'continent' => 'Americas'],
            ['iso_code_2' => 'SR', 'iso_code_3' => 'SUR', 'name_en' => 'Suriname',             'name_ar' => 'سورينام',              'flag_emoji' => '🇸🇷', 'continent' => 'Americas'],
            ['iso_code_2' => 'TT', 'iso_code_3' => 'TTO', 'name_en' => 'Trinidad and Tobago',  'name_ar' => 'ترينيداد وتوباغو',     'flag_emoji' => '🇹🇹', 'continent' => 'Americas'],
            ['iso_code_2' => 'US', 'iso_code_3' => 'USA', 'name_en' => 'United States',        'name_ar' => 'الولايات المتحدة',     'flag_emoji' => '🇺🇸', 'continent' => 'Americas'],
            ['iso_code_2' => 'UY', 'iso_code_3' => 'URY', 'name_en' => 'Uruguay',              'name_ar' => 'أوروغواي',             'flag_emoji' => '🇺🇾', 'continent' => 'Americas'],
            ['iso_code_2' => 'VE', 'iso_code_3' => 'VEN', 'name_en' => 'Venezuela',            'name_ar' => 'فنزويلا',              'flag_emoji' => '🇻🇪', 'continent' => 'Americas'],

            // ── Asia ─────────────────────────────────────────────────────────
            ['iso_code_2' => 'AF', 'iso_code_3' => 'AFG', 'name_en' => 'Afghanistan',          'name_ar' => 'أفغانستان',            'flag_emoji' => '🇦🇫', 'continent' => 'Asia'],
            ['iso_code_2' => 'AM', 'iso_code_3' => 'ARM', 'name_en' => 'Armenia',              'name_ar' => 'أرمينيا',              'flag_emoji' => '🇦🇲', 'continent' => 'Asia'],
            ['iso_code_2' => 'AZ', 'iso_code_3' => 'AZE', 'name_en' => 'Azerbaijan',           'name_ar' => 'أذربيجان',             'flag_emoji' => '🇦🇿', 'continent' => 'Asia'],
            ['iso_code_2' => 'BH', 'iso_code_3' => 'BHR', 'name_en' => 'Bahrain',              'name_ar' => 'البحرين',              'flag_emoji' => '🇧🇭', 'continent' => 'Asia'],
            ['iso_code_2' => 'BD', 'iso_code_3' => 'BGD', 'name_en' => 'Bangladesh',           'name_ar' => 'بنغلاديش',             'flag_emoji' => '🇧🇩', 'continent' => 'Asia'],
            ['iso_code_2' => 'BT', 'iso_code_3' => 'BTN', 'name_en' => 'Bhutan',               'name_ar' => 'بوتان',                'flag_emoji' => '🇧🇹', 'continent' => 'Asia'],
            ['iso_code_2' => 'BN', 'iso_code_3' => 'BRN', 'name_en' => 'Brunei',               'name_ar' => 'بروناي',               'flag_emoji' => '🇧🇳', 'continent' => 'Asia'],
            ['iso_code_2' => 'KH', 'iso_code_3' => 'KHM', 'name_en' => 'Cambodia',             'name_ar' => 'كمبوديا',              'flag_emoji' => '🇰🇭', 'continent' => 'Asia'],
            ['iso_code_2' => 'CN', 'iso_code_3' => 'CHN', 'name_en' => 'China',                'name_ar' => 'الصين',                'flag_emoji' => '🇨🇳', 'continent' => 'Asia'],
            ['iso_code_2' => 'CY', 'iso_code_3' => 'CYP', 'name_en' => 'Cyprus',               'name_ar' => 'قبرص',                 'flag_emoji' => '🇨🇾', 'continent' => 'Asia'],
            ['iso_code_2' => 'GE', 'iso_code_3' => 'GEO', 'name_en' => 'Georgia',              'name_ar' => 'جورجيا',               'flag_emoji' => '🇬🇪', 'continent' => 'Asia'],
            ['iso_code_2' => 'IN', 'iso_code_3' => 'IND', 'name_en' => 'India',                'name_ar' => 'الهند',                'flag_emoji' => '🇮🇳', 'continent' => 'Asia'],
            ['iso_code_2' => 'ID', 'iso_code_3' => 'IDN', 'name_en' => 'Indonesia',            'name_ar' => 'إندونيسيا',            'flag_emoji' => '🇮🇩', 'continent' => 'Asia'],
            ['iso_code_2' => 'IR', 'iso_code_3' => 'IRN', 'name_en' => 'Iran',                 'name_ar' => 'إيران',                'flag_emoji' => '🇮🇷', 'continent' => 'Asia'],
            ['iso_code_2' => 'IQ', 'iso_code_3' => 'IRQ', 'name_en' => 'Iraq',                 'name_ar' => 'العراق',               'flag_emoji' => '🇮🇶', 'continent' => 'Asia'],
            ['iso_code_2' => 'IL', 'iso_code_3' => 'ISR', 'name_en' => 'Israel',               'name_ar' => 'إسرائيل',              'flag_emoji' => '🇮🇱', 'continent' => 'Asia'],
            ['iso_code_2' => 'JP', 'iso_code_3' => 'JPN', 'name_en' => 'Japan',                'name_ar' => 'اليابان',              'flag_emoji' => '🇯🇵', 'continent' => 'Asia'],
            ['iso_code_2' => 'JO', 'iso_code_3' => 'JOR', 'name_en' => 'Jordan',               'name_ar' => 'الأردن',               'flag_emoji' => '🇯🇴', 'continent' => 'Asia'],
            ['iso_code_2' => 'KZ', 'iso_code_3' => 'KAZ', 'name_en' => 'Kazakhstan',           'name_ar' => 'كازاخستان',            'flag_emoji' => '🇰🇿', 'continent' => 'Asia'],
            ['iso_code_2' => 'KW', 'iso_code_3' => 'KWT', 'name_en' => 'Kuwait',               'name_ar' => 'الكويت',               'flag_emoji' => '🇰🇼', 'continent' => 'Asia'],
            ['iso_code_2' => 'KG', 'iso_code_3' => 'KGZ', 'name_en' => 'Kyrgyzstan',           'name_ar' => 'قيرغيزستان',           'flag_emoji' => '🇰🇬', 'continent' => 'Asia'],
            ['iso_code_2' => 'LA', 'iso_code_3' => 'LAO', 'name_en' => 'Laos',                 'name_ar' => 'لاوس',                 'flag_emoji' => '🇱🇦', 'continent' => 'Asia'],
            ['iso_code_2' => 'LB', 'iso_code_3' => 'LBN', 'name_en' => 'Lebanon',              'name_ar' => 'لبنان',                'flag_emoji' => '🇱🇧', 'continent' => 'Asia'],
            ['iso_code_2' => 'MY', 'iso_code_3' => 'MYS', 'name_en' => 'Malaysia',             'name_ar' => 'ماليزيا',              'flag_emoji' => '🇲🇾', 'continent' => 'Asia'],
            ['iso_code_2' => 'MV', 'iso_code_3' => 'MDV', 'name_en' => 'Maldives',             'name_ar' => 'جزر المالديف',         'flag_emoji' => '🇲🇻', 'continent' => 'Asia'],
            ['iso_code_2' => 'MN', 'iso_code_3' => 'MNG', 'name_en' => 'Mongolia',             'name_ar' => 'منغوليا',              'flag_emoji' => '🇲🇳', 'continent' => 'Asia'],
            ['iso_code_2' => 'MM', 'iso_code_3' => 'MMR', 'name_en' => 'Myanmar',              'name_ar' => 'ميانمار',              'flag_emoji' => '🇲🇲', 'continent' => 'Asia'],
            ['iso_code_2' => 'NP', 'iso_code_3' => 'NPL', 'name_en' => 'Nepal',                'name_ar' => 'نيبال',                'flag_emoji' => '🇳🇵', 'continent' => 'Asia'],
            ['iso_code_2' => 'KP', 'iso_code_3' => 'PRK', 'name_en' => 'North Korea',          'name_ar' => 'كوريا الشمالية',       'flag_emoji' => '🇰🇵', 'continent' => 'Asia'],
            ['iso_code_2' => 'OM', 'iso_code_3' => 'OMN', 'name_en' => 'Oman',                 'name_ar' => 'عُمان',                'flag_emoji' => '🇴🇲', 'continent' => 'Asia'],
            ['iso_code_2' => 'PK', 'iso_code_3' => 'PAK', 'name_en' => 'Pakistan',             'name_ar' => 'باكستان',              'flag_emoji' => '🇵🇰', 'continent' => 'Asia'],
            ['iso_code_2' => 'PS', 'iso_code_3' => 'PSE', 'name_en' => 'Palestine',            'name_ar' => 'فلسطين',               'flag_emoji' => '🇵🇸', 'continent' => 'Asia'],
            ['iso_code_2' => 'PH', 'iso_code_3' => 'PHL', 'name_en' => 'Philippines',          'name_ar' => 'الفلبين',              'flag_emoji' => '🇵🇭', 'continent' => 'Asia'],
            ['iso_code_2' => 'QA', 'iso_code_3' => 'QAT', 'name_en' => 'Qatar',                'name_ar' => 'قطر',                  'flag_emoji' => '🇶🇦', 'continent' => 'Asia'],
            ['iso_code_2' => 'SA', 'iso_code_3' => 'SAU', 'name_en' => 'Saudi Arabia',         'name_ar' => 'المملكة العربية السعودية','flag_emoji' => '🇸🇦', 'continent' => 'Asia'],
            ['iso_code_2' => 'SG', 'iso_code_3' => 'SGP', 'name_en' => 'Singapore',            'name_ar' => 'سنغافورة',             'flag_emoji' => '🇸🇬', 'continent' => 'Asia'],
            ['iso_code_2' => 'KR', 'iso_code_3' => 'KOR', 'name_en' => 'South Korea',          'name_ar' => 'كوريا الجنوبية',       'flag_emoji' => '🇰🇷', 'continent' => 'Asia'],
            ['iso_code_2' => 'LK', 'iso_code_3' => 'LKA', 'name_en' => 'Sri Lanka',            'name_ar' => 'سريلانكا',             'flag_emoji' => '🇱🇰', 'continent' => 'Asia'],
            ['iso_code_2' => 'SY', 'iso_code_3' => 'SYR', 'name_en' => 'Syria',                'name_ar' => 'سوريا',                'flag_emoji' => '🇸🇾', 'continent' => 'Asia'],
            ['iso_code_2' => 'TW', 'iso_code_3' => 'TWN', 'name_en' => 'Taiwan',               'name_ar' => 'تايوان',               'flag_emoji' => '🇹🇼', 'continent' => 'Asia'],
            ['iso_code_2' => 'TJ', 'iso_code_3' => 'TJK', 'name_en' => 'Tajikistan',           'name_ar' => 'طاجيكستان',            'flag_emoji' => '🇹🇯', 'continent' => 'Asia'],
            ['iso_code_2' => 'TH', 'iso_code_3' => 'THA', 'name_en' => 'Thailand',             'name_ar' => 'تايلاند',              'flag_emoji' => '🇹🇭', 'continent' => 'Asia'],
            ['iso_code_2' => 'TL', 'iso_code_3' => 'TLS', 'name_en' => 'Timor-Leste',          'name_ar' => 'تيمور الشرقية',        'flag_emoji' => '🇹🇱', 'continent' => 'Asia'],
            ['iso_code_2' => 'TR', 'iso_code_3' => 'TUR', 'name_en' => 'Turkey',               'name_ar' => 'تركيا',                'flag_emoji' => '🇹🇷', 'continent' => 'Asia'],
            ['iso_code_2' => 'TM', 'iso_code_3' => 'TKM', 'name_en' => 'Turkmenistan',         'name_ar' => 'تركمانستان',           'flag_emoji' => '🇹🇲', 'continent' => 'Asia'],
            ['iso_code_2' => 'AE', 'iso_code_3' => 'ARE', 'name_en' => 'United Arab Emirates', 'name_ar' => 'الإمارات العربية المتحدة','flag_emoji' => '🇦🇪', 'continent' => 'Asia'],
            ['iso_code_2' => 'UZ', 'iso_code_3' => 'UZB', 'name_en' => 'Uzbekistan',           'name_ar' => 'أوزبكستان',            'flag_emoji' => '🇺🇿', 'continent' => 'Asia'],
            ['iso_code_2' => 'VN', 'iso_code_3' => 'VNM', 'name_en' => 'Vietnam',              'name_ar' => 'فيتنام',               'flag_emoji' => '🇻🇳', 'continent' => 'Asia'],
            ['iso_code_2' => 'YE', 'iso_code_3' => 'YEM', 'name_en' => 'Yemen',                'name_ar' => 'اليمن',                'flag_emoji' => '🇾🇪', 'continent' => 'Asia'],

            // ── Europe ────────────────────────────────────────────────────────
            ['iso_code_2' => 'AL', 'iso_code_3' => 'ALB', 'name_en' => 'Albania',              'name_ar' => 'ألبانيا',              'flag_emoji' => '🇦🇱', 'continent' => 'Europe'],
            ['iso_code_2' => 'AD', 'iso_code_3' => 'AND', 'name_en' => 'Andorra',              'name_ar' => 'أندورا',               'flag_emoji' => '🇦🇩', 'continent' => 'Europe'],
            ['iso_code_2' => 'AT', 'iso_code_3' => 'AUT', 'name_en' => 'Austria',              'name_ar' => 'النمسا',               'flag_emoji' => '🇦🇹', 'continent' => 'Europe'],
            ['iso_code_2' => 'BY', 'iso_code_3' => 'BLR', 'name_en' => 'Belarus',              'name_ar' => 'بيلاروسيا',            'flag_emoji' => '🇧🇾', 'continent' => 'Europe'],
            ['iso_code_2' => 'BE', 'iso_code_3' => 'BEL', 'name_en' => 'Belgium',              'name_ar' => 'بلجيكا',               'flag_emoji' => '🇧🇪', 'continent' => 'Europe'],
            ['iso_code_2' => 'BA', 'iso_code_3' => 'BIH', 'name_en' => 'Bosnia and Herzegovina','name_ar' => 'البوسنة والهرسك',     'flag_emoji' => '🇧🇦', 'continent' => 'Europe'],
            ['iso_code_2' => 'BG', 'iso_code_3' => 'BGR', 'name_en' => 'Bulgaria',             'name_ar' => 'بلغاريا',              'flag_emoji' => '🇧🇬', 'continent' => 'Europe'],
            ['iso_code_2' => 'HR', 'iso_code_3' => 'HRV', 'name_en' => 'Croatia',              'name_ar' => 'كرواتيا',              'flag_emoji' => '🇭🇷', 'continent' => 'Europe'],
            ['iso_code_2' => 'CZ', 'iso_code_3' => 'CZE', 'name_en' => 'Czech Republic',       'name_ar' => 'جمهورية التشيك',       'flag_emoji' => '🇨🇿', 'continent' => 'Europe'],
            ['iso_code_2' => 'DK', 'iso_code_3' => 'DNK', 'name_en' => 'Denmark',              'name_ar' => 'الدنمارك',             'flag_emoji' => '🇩🇰', 'continent' => 'Europe'],
            ['iso_code_2' => 'EE', 'iso_code_3' => 'EST', 'name_en' => 'Estonia',              'name_ar' => 'إستونيا',              'flag_emoji' => '🇪🇪', 'continent' => 'Europe'],
            ['iso_code_2' => 'FI', 'iso_code_3' => 'FIN', 'name_en' => 'Finland',              'name_ar' => 'فنلندا',               'flag_emoji' => '🇫🇮', 'continent' => 'Europe'],
            ['iso_code_2' => 'FR', 'iso_code_3' => 'FRA', 'name_en' => 'France',               'name_ar' => 'فرنسا',                'flag_emoji' => '🇫🇷', 'continent' => 'Europe'],
            ['iso_code_2' => 'DE', 'iso_code_3' => 'DEU', 'name_en' => 'Germany',              'name_ar' => 'ألمانيا',              'flag_emoji' => '🇩🇪', 'continent' => 'Europe'],
            ['iso_code_2' => 'GR', 'iso_code_3' => 'GRC', 'name_en' => 'Greece',               'name_ar' => 'اليونان',              'flag_emoji' => '🇬🇷', 'continent' => 'Europe'],
            ['iso_code_2' => 'HU', 'iso_code_3' => 'HUN', 'name_en' => 'Hungary',              'name_ar' => 'المجر',                'flag_emoji' => '🇭🇺', 'continent' => 'Europe'],
            ['iso_code_2' => 'IS', 'iso_code_3' => 'ISL', 'name_en' => 'Iceland',              'name_ar' => 'آيسلندا',              'flag_emoji' => '🇮🇸', 'continent' => 'Europe'],
            ['iso_code_2' => 'IE', 'iso_code_3' => 'IRL', 'name_en' => 'Ireland',              'name_ar' => 'أيرلندا',              'flag_emoji' => '🇮🇪', 'continent' => 'Europe'],
            ['iso_code_2' => 'IT', 'iso_code_3' => 'ITA', 'name_en' => 'Italy',                'name_ar' => 'إيطاليا',              'flag_emoji' => '🇮🇹', 'continent' => 'Europe'],
            ['iso_code_2' => 'XK', 'iso_code_3' => 'XKX', 'name_en' => 'Kosovo',               'name_ar' => 'كوسوفو',               'flag_emoji' => '🇽🇰', 'continent' => 'Europe'],
            ['iso_code_2' => 'LV', 'iso_code_3' => 'LVA', 'name_en' => 'Latvia',               'name_ar' => 'لاتفيا',               'flag_emoji' => '🇱🇻', 'continent' => 'Europe'],
            ['iso_code_2' => 'LI', 'iso_code_3' => 'LIE', 'name_en' => 'Liechtenstein',        'name_ar' => 'ليختنشتاين',           'flag_emoji' => '🇱🇮', 'continent' => 'Europe'],
            ['iso_code_2' => 'LT', 'iso_code_3' => 'LTU', 'name_en' => 'Lithuania',            'name_ar' => 'ليتوانيا',             'flag_emoji' => '🇱🇹', 'continent' => 'Europe'],
            ['iso_code_2' => 'LU', 'iso_code_3' => 'LUX', 'name_en' => 'Luxembourg',           'name_ar' => 'لوكسمبورغ',            'flag_emoji' => '🇱🇺', 'continent' => 'Europe'],
            ['iso_code_2' => 'MT', 'iso_code_3' => 'MLT', 'name_en' => 'Malta',                'name_ar' => 'مالطا',                'flag_emoji' => '🇲🇹', 'continent' => 'Europe'],
            ['iso_code_2' => 'MD', 'iso_code_3' => 'MDA', 'name_en' => 'Moldova',              'name_ar' => 'مولدوفا',              'flag_emoji' => '🇲🇩', 'continent' => 'Europe'],
            ['iso_code_2' => 'MC', 'iso_code_3' => 'MCO', 'name_en' => 'Monaco',               'name_ar' => 'موناكو',               'flag_emoji' => '🇲🇨', 'continent' => 'Europe'],
            ['iso_code_2' => 'ME', 'iso_code_3' => 'MNE', 'name_en' => 'Montenegro',           'name_ar' => 'الجبل الأسود',         'flag_emoji' => '🇲🇪', 'continent' => 'Europe'],
            ['iso_code_2' => 'NL', 'iso_code_3' => 'NLD', 'name_en' => 'Netherlands',          'name_ar' => 'هولندا',               'flag_emoji' => '🇳🇱', 'continent' => 'Europe'],
            ['iso_code_2' => 'MK', 'iso_code_3' => 'MKD', 'name_en' => 'North Macedonia',      'name_ar' => 'مقدونيا الشمالية',     'flag_emoji' => '🇲🇰', 'continent' => 'Europe'],
            ['iso_code_2' => 'NO', 'iso_code_3' => 'NOR', 'name_en' => 'Norway',               'name_ar' => 'النرويج',              'flag_emoji' => '🇳🇴', 'continent' => 'Europe'],
            ['iso_code_2' => 'PL', 'iso_code_3' => 'POL', 'name_en' => 'Poland',               'name_ar' => 'بولندا',               'flag_emoji' => '🇵🇱', 'continent' => 'Europe'],
            ['iso_code_2' => 'PT', 'iso_code_3' => 'PRT', 'name_en' => 'Portugal',             'name_ar' => 'البرتغال',             'flag_emoji' => '🇵🇹', 'continent' => 'Europe'],
            ['iso_code_2' => 'RO', 'iso_code_3' => 'ROU', 'name_en' => 'Romania',              'name_ar' => 'رومانيا',              'flag_emoji' => '🇷🇴', 'continent' => 'Europe'],
            ['iso_code_2' => 'RU', 'iso_code_3' => 'RUS', 'name_en' => 'Russia',               'name_ar' => 'روسيا',                'flag_emoji' => '🇷🇺', 'continent' => 'Europe'],
            ['iso_code_2' => 'SM', 'iso_code_3' => 'SMR', 'name_en' => 'San Marino',           'name_ar' => 'سان مارينو',           'flag_emoji' => '🇸🇲', 'continent' => 'Europe'],
            ['iso_code_2' => 'RS', 'iso_code_3' => 'SRB', 'name_en' => 'Serbia',               'name_ar' => 'صربيا',                'flag_emoji' => '🇷🇸', 'continent' => 'Europe'],
            ['iso_code_2' => 'SK', 'iso_code_3' => 'SVK', 'name_en' => 'Slovakia',             'name_ar' => 'سلوفاكيا',             'flag_emoji' => '🇸🇰', 'continent' => 'Europe'],
            ['iso_code_2' => 'SI', 'iso_code_3' => 'SVN', 'name_en' => 'Slovenia',             'name_ar' => 'سلوفينيا',             'flag_emoji' => '🇸🇮', 'continent' => 'Europe'],
            ['iso_code_2' => 'ES', 'iso_code_3' => 'ESP', 'name_en' => 'Spain',                'name_ar' => 'إسبانيا',              'flag_emoji' => '🇪🇸', 'continent' => 'Europe'],
            ['iso_code_2' => 'SE', 'iso_code_3' => 'SWE', 'name_en' => 'Sweden',               'name_ar' => 'السويد',               'flag_emoji' => '🇸🇪', 'continent' => 'Europe'],
            ['iso_code_2' => 'CH', 'iso_code_3' => 'CHE', 'name_en' => 'Switzerland',          'name_ar' => 'سويسرا',               'flag_emoji' => '🇨🇭', 'continent' => 'Europe'],
            ['iso_code_2' => 'UA', 'iso_code_3' => 'UKR', 'name_en' => 'Ukraine',              'name_ar' => 'أوكرانيا',             'flag_emoji' => '🇺🇦', 'continent' => 'Europe'],
            ['iso_code_2' => 'GB', 'iso_code_3' => 'GBR', 'name_en' => 'United Kingdom',       'name_ar' => 'المملكة المتحدة',      'flag_emoji' => '🇬🇧', 'continent' => 'Europe'],
            ['iso_code_2' => 'VA', 'iso_code_3' => 'VAT', 'name_en' => 'Vatican City',         'name_ar' => 'الفاتيكان',            'flag_emoji' => '🇻🇦', 'continent' => 'Europe'],

            // ── Oceania ───────────────────────────────────────────────────────
            ['iso_code_2' => 'AU', 'iso_code_3' => 'AUS', 'name_en' => 'Australia',            'name_ar' => 'أستراليا',             'flag_emoji' => '🇦🇺', 'continent' => 'Oceania'],
            ['iso_code_2' => 'FJ', 'iso_code_3' => 'FJI', 'name_en' => 'Fiji',                 'name_ar' => 'فيجي',                 'flag_emoji' => '🇫🇯', 'continent' => 'Oceania'],
            ['iso_code_2' => 'KI', 'iso_code_3' => 'KIR', 'name_en' => 'Kiribati',             'name_ar' => 'كيريباتي',             'flag_emoji' => '🇰🇮', 'continent' => 'Oceania'],
            ['iso_code_2' => 'MH', 'iso_code_3' => 'MHL', 'name_en' => 'Marshall Islands',     'name_ar' => 'جزر مارشال',           'flag_emoji' => '🇲🇭', 'continent' => 'Oceania'],
            ['iso_code_2' => 'FM', 'iso_code_3' => 'FSM', 'name_en' => 'Micronesia',           'name_ar' => 'ميكرونيزيا',           'flag_emoji' => '🇫🇲', 'continent' => 'Oceania'],
            ['iso_code_2' => 'NR', 'iso_code_3' => 'NRU', 'name_en' => 'Nauru',                'name_ar' => 'ناورو',                'flag_emoji' => '🇳🇷', 'continent' => 'Oceania'],
            ['iso_code_2' => 'NZ', 'iso_code_3' => 'NZL', 'name_en' => 'New Zealand',          'name_ar' => 'نيوزيلندا',            'flag_emoji' => '🇳🇿', 'continent' => 'Oceania'],
            ['iso_code_2' => 'PW', 'iso_code_3' => 'PLW', 'name_en' => 'Palau',                'name_ar' => 'بالاو',                'flag_emoji' => '🇵🇼', 'continent' => 'Oceania'],
            ['iso_code_2' => 'PG', 'iso_code_3' => 'PNG', 'name_en' => 'Papua New Guinea',     'name_ar' => 'بابوا غينيا الجديدة',  'flag_emoji' => '🇵🇬', 'continent' => 'Oceania'],
            ['iso_code_2' => 'WS', 'iso_code_3' => 'WSM', 'name_en' => 'Samoa',                'name_ar' => 'ساموا',                'flag_emoji' => '🇼🇸', 'continent' => 'Oceania'],
            ['iso_code_2' => 'SB', 'iso_code_3' => 'SLB', 'name_en' => 'Solomon Islands',      'name_ar' => 'جزر سليمان',           'flag_emoji' => '🇸🇧', 'continent' => 'Oceania'],
            ['iso_code_2' => 'TO', 'iso_code_3' => 'TON', 'name_en' => 'Tonga',                'name_ar' => 'تونغا',                'flag_emoji' => '🇹🇴', 'continent' => 'Oceania'],
            ['iso_code_2' => 'TV', 'iso_code_3' => 'TUV', 'name_en' => 'Tuvalu',               'name_ar' => 'توفالو',               'flag_emoji' => '🇹🇻', 'continent' => 'Oceania'],
            ['iso_code_2' => 'VU', 'iso_code_3' => 'VUT', 'name_en' => 'Vanuatu',              'name_ar' => 'فانواتو',              'flag_emoji' => '🇻🇺', 'continent' => 'Oceania'],
        ];
    }
}
