import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { getLocale } from "next-intl/server";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";
import RootProviders from "@/src/providers";

import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import "swiper/css/grid";
import "./globals.css";

import getLocale from "@/src/helpers/getLocale";
import AuthDialog from "@/src/components/shared/dialogs/AuthDialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="pb-15 md:pb-0">
        <NextTopLoader color="#111111" showSpinner={false} />
        <RootProviders>
          <Toaster position="bottom-right" />
          {children}
          {/* dialogs */}
          <AuthDialog />
        </RootProviders>
      </body>
    </html>
  );
}
